"""Static checks that keep the shipped UI wired to the API it renders.

The workspace is a hand-written static bundle with no build step, so a typo in
an element id or a CSS class name fails silently in the browser instead of at
import time.  These tests pin the contract between markup, script, and stylesheet.
"""

import re
from pathlib import Path

import pytest

UI_DIR = Path(__file__).resolve().parents[1] / "docs" / "ui"
WORKSPACE = UI_DIR / "workspace-v4.html"
SCRIPT = UI_DIR / "workspace.js"
STYLESHEET = UI_DIR / "workspace.css"


@pytest.fixture(scope="module")
def workspace() -> str:
    return WORKSPACE.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def script() -> str:
    return SCRIPT.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def stylesheet() -> str:
    return STYLESHEET.read_text(encoding="utf-8")


def test_workspace_loads_static_assets(workspace: str) -> None:
    assert 'href="workspace.css"' in workspace
    assert 'src="workspace.js"' in workspace
    assert SCRIPT.is_file()
    assert STYLESHEET.is_file()


def test_root_redirect_target_exists() -> None:
    """`GET /` redirects here, so the file must ship under the mounted directory."""
    api_source = (
        Path(__file__).resolve().parents[1] / "src" / "findoc_rag" / "api.py"
    ).read_text(encoding="utf-8")
    targets = re.findall(r'RedirectResponse\("/ui/([^"]+)"\)', api_source)
    assert targets, "api.py no longer redirects to a /ui page"
    for target in targets:
        assert (UI_DIR / target).is_file(), f"/ui/{target} is missing"


def test_every_scripted_element_id_exists(workspace: str, script: str) -> None:
    declared = set(re.findall(r'\bid="([^"]+)"', workspace))
    referenced = set(re.findall(r'\$\("([^"]+)"\)', script))
    assert not referenced - declared, "script reads element ids that the markup never defines"


def test_element_ids_are_unique(workspace: str) -> None:
    declared = re.findall(r'\bid="([^"]+)"', workspace)
    duplicates = {name for name in declared if declared.count(name) > 1}
    assert not duplicates, f"duplicate element ids: {sorted(duplicates)}"


def test_tab_and_panel_ids_pair_up(workspace: str, script: str) -> None:
    controls = set(re.findall(r'data-panel="([^"]+)"', workspace))
    contents = set(re.findall(r'data-panel-content="([^"]+)"', workspace))
    assert controls
    assert controls == contents
    titles = re.search(r"const PANEL_TITLES = \{(.*?)\};", script, re.DOTALL)
    assert titles, "PANEL_TITLES is missing"
    declared = set(re.findall(r"\b([a-z][a-z0-9_]*)\s*:", titles.group(1)))
    assert controls == declared


def test_generated_class_names_are_styled(script: str, stylesheet: str) -> None:
    """Every outcome class generated by the script must have a CSS treatment."""
    outcomes = re.search(r"const OUTCOME = \{(.*?)\};", script, re.DOTALL)
    assert outcomes, "OUTCOME mapping is missing"
    used = set(re.findall(r':\s*\["[^"]+",\s*"([^"]+)"\]', outcomes.group(1)))
    used.update({"running", "error"})
    missing = {name for name in used if f".outcome-badge.{name}" not in stylesheet}
    assert not missing, f"unstyled outcome classes: {sorted(missing)}"


def test_query_uses_capability_declared_modes(workspace: str, script: str) -> None:
    """Retrieval modes must come from /v1/capabilities, not a hardcoded list, so a
    lexical-only index never offers dense/hybrid options that are certain to fail."""
    assert "capabilities?.modes" in script
    assert "modes.map" in script, "mode options are not derived from the declared modes"
    hardcoded = re.findall(r'<option value="(dense|hybrid)"', workspace)
    assert not hardcoded, f"retrieval modes hardcoded in markup: {sorted(set(hardcoded))}"


def test_endpoints_called_by_ui_are_served_by_the_api(script: str) -> None:
    api_source = (
        Path(__file__).resolve().parents[1] / "src" / "findoc_rag" / "api.py"
    ).read_text(encoding="utf-8")
    called = set(re.findall(r'"(/(?:v1|health)/[a-z:_]+)', script))
    assert called, "the UI calls no API endpoints"
    for path in called:
        assert f'"{path}' in api_source, f"UI calls {path} but api.py does not route it"


def test_dead_prototypes_are_gone() -> None:
    for name in ("workspace-v2.html", "workspace-v3.html", "workspace-wireframe.html"):
        assert not (UI_DIR / name).exists(), f"{name} was superseded and should not return"
